apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-k8
  template:
    metadata:
      labels:
        app: spring-k8
    spec:
      containers:
        - name: spring-k8
          image: kashish2597/spring-k8:latest
          ports:
            - containerPort: 8080

